name: CD

on:
  push:
    branches: ['master']

jobs:
  
  setup:
    name: Setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: yarn
  build:
    name: Build
    needs: setup
    steps:
      - name: Build
        run: yarn build
  deploy:
    name: Deploy
    needs: build
    steps:
      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.SFTP_USERNAME }}'
          server: '${{ secrets.SFTP_SERVER }}'
          port: '${{ secrets.SFTP_PORT }}'
          ssh_private_key: ${{ secrets.SFTP_PRIVKEY }} 
          local_path: './dist/*'
          remote_path: '/var/www/i.alru.xyz'
          args: '-o ConnectTimeout=5'
